# Generated by Django 4.0.4 on 2022-04-17 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=300)),
                ('corpo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('bloco', models.CharField(max_length=50)),
                ('apartamento', models.IntegerField()),
                ('interfone', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sindico', models.BooleanField(verbose_name='É síndico?')),
                ('usuario_criado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Moradores',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data e horário da reunião')),
                ('assunto', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Reunioes',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quatroestacoes.morador', verbose_name='ID do morador')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão')], max_length=50)),
                ('assunto', models.CharField(max_length=300)),
                ('corpo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quatroestacoes.morador', verbose_name='ID do morador')),
            ],
            options={
                'verbose_name_plural': 'Reclamacoes',
            },
        ),
    ]
