# Generated by Django 4.0.4 on 2022-04-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Morador',
            new_name='Moradores',
        ),
    ]
