# Generated by Django 4.0.4 on 2022-04-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='apartamento',
            field=models.IntegerField(choices=[(1, '01'), (2, '02'), (11, '11'), (12, '12'), (21, '21'), (22, '22'), (31, '31'), (32, '32')]),
        ),
        migrations.AlterField(
            model_name='morador',
            name='bloco',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50),
        ),
    ]
