# Generated by Django 4.0.4 on 2022-05-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='celular',
            field=models.BigIntegerField(),
        ),
    ]
