# Generated by Django 4.0.4 on 2022-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0002_alter_morador_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
