# Generated by Django 4.0.4 on 2022-04-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0002_alter_morador_apartamento_alter_morador_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacao',
            name='morador',
        ),
    ]
