# Generated by Django 4.0.4 on 2022-04-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0002_rename_morador_moradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=300)),
                ('corpo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reunioes',
            fields=[
                ('id_reuniao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(verbose_name='Data e horário da reunião')),
                ('assunto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quatroestacoes.moradores', verbose_name='ID do morador')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id_reclamacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão')], max_length=50)),
                ('assunto', models.CharField(max_length=300)),
                ('corpo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quatroestacoes.moradores', verbose_name='ID do morador')),
            ],
        ),
    ]
