# Generated by Django 4.0.4 on 2022-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0003_avisos_reunioes_reservas_reclamacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avisos',
            new_name='Aviso',
        ),
        migrations.RenameModel(
            old_name='Reclamacoes',
            new_name='Reclamacao',
        ),
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
        migrations.RenameModel(
            old_name='Reunioes',
            new_name='Reuniao',
        ),
        migrations.AlterField(
            model_name='moradores',
            name='sindico',
            field=models.BooleanField(verbose_name='É síndico?'),
        ),
    ]
