# Generated by Django 4.0.4 on 2022-05-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0003_alter_morador_first_name_alter_morador_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
