# Generated by Django 4.0.4 on 2022-04-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0003_remove_reclamacao_morador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='usuario_criado',
        ),
    ]
