# Generated by Django 4.0.4 on 2022-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0004_remove_morador_usuario_criado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='sindico',
        ),
    ]
