# Generated by Django 4.0.4 on 2022-04-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0004_rename_avisos_aviso_rename_reclamacoes_reclamacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moradores',
            options={'verbose_name_plural': 'Moradores'},
        ),
        migrations.AlterModelOptions(
            name='reclamacao',
            options={'verbose_name_plural': 'Reclamacoes'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name_plural': 'Reunioes'},
        ),
    ]
