# Generated by Django 4.0.4 on 2022-04-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quatroestacoes', '0005_alter_moradores_options_alter_reclamacao_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moradores',
            new_name='Morador',
        ),
    ]
